name: Tests

on:
  pull_request:
    paths:
      - '**/*.lua'
      - '.github/workflows/ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  x64-ubuntu:
    name: X64-ubuntu
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: date +%F > todays-date
      - name: Restore cache for today's nightly.
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: _neovim
          key: ${{ runner.os }}-v0.10.4-${{ hashFiles('todays-date') }}

      - name: Cache cargo
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-tree-sitter-cli

      - name: Install tree-sitter-cli
        run: |
          if ! command -v tree-sitter &> /dev/null; then
            cargo install tree-sitter-cli
          fi

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y fd-find
          test -d _neovim || {
            mkdir -p _neovim
            curl -sL https://github.com/neovim/neovim/releases/download/v0.10.4/nvim-linux-x86_64.tar.gz | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          }

      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIMRUNTIME="${PWD}/_neovim/share/nvim/runtime"
          make test
